INTERFACE Z100085_zif_proubc_Ident PUBLIC.
* Generated by abap-openapi-client
* Ident, 1.0

* Component schema: CreateapplicationRequest, object
  TYPES: BEGIN OF createapplicationrequest,
           name TYPE string,
         END OF createapplicationrequest.

* Component schema: AssociateusertoapplicationRequest, object
  TYPES: BEGIN OF associateusertoapplicationrequ,
           user_id TYPE string,
         END OF associateusertoapplicationrequ.

* Component schema: UpdateapplicationRequest, object
  TYPES: BEGIN OF updateapplicationrequest,
           name TYPE string,
           description TYPE string,
           type TYPE string,
           hidden TYPE abap_bool,
         END OF updateapplicationrequest.

* Component schema: CreateorganizationRequest, object
  TYPES: BEGIN OF createorganizationrequest,
           name TYPE string,
           description TYPE string,
         END OF createorganizationrequest.

* Component schema: UpdateorganizationdetailsRequest, object
  TYPES: BEGIN OF updateorganizationdetailsreque,
           name TYPE string,
           description TYPE string,
         END OF updateorganizationdetailsreque.

* Component schema: Authorizelong-termtokenRequest, object
  TYPES: BEGIN OF authorizelong_termtokenrequest,
           scope TYPE string,
           organization_id TYPE string,
         END OF authorizelong_termtokenrequest.

* Component schema: AuthenticationRequest, object
  TYPES: BEGIN OF authenticationrequest,
           email TYPE string,
           password TYPE string,
         END OF authenticationrequest.

* Component schema: CreateuserRequest, object
  TYPES: BEGIN OF createuserrequest,
           email TYPE string,
           first_name TYPE string,
           last_name TYPE string,
         END OF createuserrequest.

* Component schema: UpdateuserRequest, object
  TYPES: BEGIN OF updateuserrequest,
           email TYPE string,
           first_name TYPE string,
           last_name TYPE string,
           password TYPE string,
         END OF updateuserrequest.

* POST - "Create application"
* Operation id: Createapplication
* Parameter: name, required, header
* Response: 200
* Body ref: #/components/schemas/CreateapplicationRequest
  METHODS createapplication
    IMPORTING
      name TYPE string
      body TYPE createapplicationrequest
    RAISING cx_static_check.

* GET - "List applications"
* Operation id: Listapplications
* Response: 200
  METHODS listapplications
    RAISING cx_static_check.

* POST - "Associate user to application"
* Operation id: Associateusertoapplication
* Parameter: application_id, required, path
* Response: 200
* Body ref: #/components/schemas/AssociateusertoapplicationRequest
  METHODS associateusertoapplication
    IMPORTING
      application_id TYPE string
      body TYPE associateusertoapplicationrequ
    RAISING cx_static_check.

* GET - "List application users"
* Operation id: Listapplicationusers
* Parameter: content-type, required, header
* Parameter: application_id, required, path
* Response: 200
  METHODS listapplicationusers
    IMPORTING
      content_type TYPE string
      application_id TYPE string
    RAISING cx_static_check.

* GET - "Get application details"
* Operation id: Getapplicationdetails
* Parameter: content-type, required, header
* Parameter: application_id, required, path
* Response: 200
  METHODS getapplicationdetails
    IMPORTING
      content_type TYPE string
      application_id TYPE string
    RAISING cx_static_check.

* PUT - "Update application"
* Operation id: Updateapplication
* Parameter: name, required, header
* Parameter: application_id, required, path
* Response: 200
* Body ref: #/components/schemas/UpdateapplicationRequest
  METHODS updateapplication
    IMPORTING
      name TYPE string
      application_id TYPE string
      body TYPE updateapplicationrequest
    RAISING cx_static_check.

* DELETE - "Delete application"
* Operation id: Deleteapplication
* Parameter: content-type, required, header
* Parameter: application_id, required, path
* Response: 200
  METHODS deleteapplication
    IMPORTING
      content_type TYPE string
      application_id TYPE string
    RAISING cx_static_check.

* GET - "List organizations"
* Operation id: Listorganizations
* Parameter: content-type, required, header
* Response: 200
  METHODS listorganizations
    IMPORTING
      content_type TYPE string
    RAISING cx_static_check.

* POST - "Create organization"
* Operation id: Createorganization
* Parameter: name, required, header
* Response: 200
* Body ref: #/components/schemas/CreateorganizationRequest
  METHODS createorganization
    IMPORTING
      name TYPE string
      body TYPE createorganizationrequest
    RAISING cx_static_check.

* GET - "Get organization details"
* Operation id: Getorganizationdetails
* Parameter: content-type, required, header
* Parameter: name, required, header
* Parameter: organization_id, required, path
* Response: 200
  METHODS getorganizationdetails
    IMPORTING
      content_type TYPE string
      name TYPE string
      organization_id TYPE string
    RAISING cx_static_check.

* PUT - "Update organization details"
* Operation id: Updateorganizationdetails
* Parameter: name, required, header
* Parameter: organization_id, required, path
* Response: 200
* Body ref: #/components/schemas/UpdateorganizationdetailsRequest
  METHODS updateorganizationdetails
    IMPORTING
      name TYPE string
      organization_id TYPE string
      body TYPE updateorganizationdetailsreque
    RAISING cx_static_check.

* GET - "List tokens"
* Operation id: Listtokens
* Parameter: content-type, required, header
* Parameter: name, required, header
* Response: 200
  METHODS listtokens
    IMPORTING
      content_type TYPE string
      name TYPE string
    RAISING cx_static_check.

* POST - "Authorize long-term token"
* Operation id: Authorizelong-termtoken
* Response: 200
* Body ref: #/components/schemas/Authorizelong-termtokenRequest
  METHODS authorizelong_termtoken
    IMPORTING
      body TYPE authorizelong_termtokenrequest
    RAISING cx_static_check.

* PUT - "Update user"
* Operation id: Updateuser
* Parameter: name, required, header
* Response: 200
* Body ref: #/components/schemas/UpdateuserRequest
  METHODS updateuser
    IMPORTING
      name TYPE string
      body TYPE updateuserrequest
    RAISING cx_static_check.

* DELETE - "Revoke token"
* Operation id: Revoketoken
* Parameter: content-type, required, header
* Response: 200
  METHODS revoketoken
    IMPORTING
      content_type TYPE string
    RAISING cx_static_check.

* POST - "Authentication"
* Operation id: Authentication
* Response: 200
* Body ref: #/components/schemas/AuthenticationRequest
  METHODS authentication
    IMPORTING
      body TYPE authenticationrequest
    RAISING cx_static_check.

* GET - "List users Copy"
* Operation id: ListusersCopy
* Parameter: content-type, required, header
* Response: 200
  METHODS listuserscopy
    IMPORTING
      content_type TYPE string
    RAISING cx_static_check.

* POST - "Create user"
* Operation id: Createuser
* Response: 200
* Body ref: #/components/schemas/CreateuserRequest
  METHODS createuser
    IMPORTING
      body TYPE createuserrequest
    RAISING cx_static_check.

* GET - "Get user detail"
* Operation id: Getuserdetail
* Parameter: content-type, required, header
* Parameter: name, required, header
* Parameter: user_id, required, path
* Response: 200
  METHODS getuserdetail
    IMPORTING
      content_type TYPE string
      name TYPE string
      user_id TYPE string
    RAISING cx_static_check.

* DELETE - "Delete user"
* Operation id: Deleteuser
* Parameter: content-type, required, header
* Parameter: user_id, required, path
* Response: 200
  METHODS deleteuser
    IMPORTING
      content_type TYPE string
      user_id TYPE string
    RAISING cx_static_check.

ENDINTERFACE.
