INTERFACE z100085_zif_proubc_vault PUBLIC.
* Generated by abap-openapi-client
* Vaults, e0f2fc37-4491-4f00-8b70-5bdcb69fd223

* POST - "Create a key: C25519"
* Operation id: Createakey:C25519
* Parameter: authorization, required, header
* Parameter: Content-Type, required, header
* Parameter: vault_id, required, path
* Response: 200
* Body schema: string
  METHODS createakey_c25519
    IMPORTING
      authorization TYPE string
      content_type TYPE string
      vault_id TYPE string
      body TYPE string
    RAISING cx_static_check.

* GET - "List keys"
* Operation id: Listkeys
* Parameter: authorization, required, header
* Parameter: Content-Type, required, header
* Parameter: vault_id, required, path
* Response: 200
* Body schema: string
  METHODS listkeys
    IMPORTING
      authorization TYPE string
      content_type TYPE string
      vault_id TYPE string
      body TYPE string
    RAISING cx_static_check.

* POST - "Derive a key: ChaCha20"
* Operation id: Deriveakey:ChaCha20
* Parameter: authorization, required, header
* Parameter: Content-Type, required, header
* Parameter: vault_id, required, path
* Response: 200
* Body schema: string
  METHODS deriveakey_chacha20
    IMPORTING
      authorization TYPE string
      content_type TYPE string
      vault_id TYPE string
      body TYPE string
    RAISING cx_static_check.

* DELETE - "Delete a key"
* Operation id: Deleteakey
* Parameter: authorization, required, header
* Parameter: Content-Type, required, header
* Parameter: vault_id, required, path
* Parameter: key_id, required, path
* Response: 200
  METHODS deleteakey
    IMPORTING
      authorization TYPE string
      content_type TYPE string
      vault_id TYPE string
      key_id TYPE string
    RAISING cx_static_check.

* GET - "List secrets"
* Operation id: Listsecrets
* Parameter: authorization, required, header
* Parameter: Content-Type, required, header
* Parameter: vault_id, required, path
* Response: 200
  METHODS listsecrets
    IMPORTING
      authorization TYPE string
      content_type TYPE string
      vault_id TYPE string
    RAISING cx_static_check.

* POST - "Retreive secret"
* Operation id: Retreivesecret
* Parameter: authorization, required, header
* Parameter: Content-Type, required, header
* Parameter: vault_id, required, path
* Parameter: secret_id, required, path
* Response: 200
* Body schema: string
  METHODS retreivesecret
    IMPORTING
      authorization TYPE string
      content_type TYPE string
      vault_id TYPE string
      secret_id TYPE string
      body TYPE string
    RAISING cx_static_check.

* DELETE - "Delete secret"
* Operation id: Deletesecret
* Parameter: authorization, required, header
* Parameter: Content-Type, required, header
* Parameter: vault_id, required, path
* Parameter: secret_id, required, path
* Response: 200
* Body schema: string
  METHODS deletesecret
    IMPORTING
      authorization TYPE string
      content_type TYPE string
      vault_id TYPE string
      secret_id TYPE string
      body TYPE string
    RAISING cx_static_check.

* POST - "Create Vault"
* Operation id: CreateVault
* Parameter: Content-Type, required, header
* Parameter: content-type, required, header
* Parameter: Authorization, required, header
* Response: 200
* Body schema: string
  METHODS createvault
    IMPORTING
      content_type TYPE string
      "content_type TYPE string //why'd this show up 2x?
      authorization TYPE string
      body TYPE string
    RAISING cx_static_check.

* GET - "List Vaults"
* Operation id: ListVaults
* Parameter: Authorization, required, header
* Response: 200
* Body schema: string
  METHODS listvaults
    IMPORTING
      authorization TYPE string
      body TYPE string
    RAISING cx_static_check.

* POST - "Create Seal/Unseal key"
* Operation id: CreateSeal/Unsealkey
* Parameter: authorization, required, header
* Parameter: Content-Type, required, header
* Response: 200
  METHODS createseal_unsealkey
    IMPORTING
      authorization TYPE string
      content_type TYPE string
    RAISING cx_static_check.

* POST - "Unseal vault"
* Operation id: Unsealvault
* Parameter: authorization, required, header
* Parameter: Content-Type, required, header
* Response: 200
* Body schema: string
  METHODS unsealvault
    IMPORTING
      authorization TYPE string
      content_type TYPE string
      body TYPE string
    RAISING cx_static_check.

ENDINTERFACE.
