CLASS z100085_zcl_proubc_bomodelapi DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS z100085_zcl_proubc_bomodelapi IMPLEMENTATION.
ENDCLASS.
