INTERFACE zif_prvd_ipfs PUBLIC.
* Auto generated by https://github.com/abap-openapi/abap-openapi

  METHODS add
    IMPORTING
      quiet               TYPE abap_bool
      quieter             TYPE abap_bool
      silent              TYPE abap_bool
      progress            TYPE abap_bool
      trickle             TYPE abap_bool
      only_hash           TYPE abap_bool
      wrap_with_directory TYPE abap_bool
      chunker             TYPE string
      pin                 TYPE abap_bool
      raw_leaves          TYPE abap_bool
      nocopy              TYPE abap_bool
      fscache             TYPE abap_bool
      cid_version         TYPE i
      hash                TYPE string
      inline              TYPE abap_bool
      inline_limit        TYPE i
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS bitswap_ledger
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS bitswap_reprovide
    RAISING
      cx_static_check.
  METHODS bitswap_stat
    IMPORTING
      verbose             TYPE abap_bool
      human               TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS bitswap_wantlist
    IMPORTING
      peer                TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS block_get
    IMPORTING
      arg TYPE string
    RAISING
      cx_static_check.
  METHODS block_put
    IMPORTING
      cid_codec           TYPE string
      mhtype              TYPE string
      mhlen               TYPE i
      pin                 TYPE abap_bool
      allow_big_block     TYPE abap_bool
      format              TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS block_rm
    IMPORTING
      arg                 TYPE string
      force               TYPE abap_bool
      quiet               TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS block_stat
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS bootstrap
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.

* todo this method doesnt want to syntax check
*  METHODS bootstrap_add
*    IMPORTING
*      arg TYPE string
*      default TYPE abap_bool
*    EXPORTING
*                  ev_apiresponsestr   TYPE string
*              ev_apiresponse      TYPE REF TO data
*              ev_httpresponsecode TYPE i
*    RAISING
*      cx_static_check.
  METHODS bootstrap_add_default
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS bootstrap_list
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS bootstrap_rm
    IMPORTING
      arg                 TYPE string
      all                 TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS bootstrap_rm_all
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS cat
    IMPORTING
      arg      TYPE string
      offset   TYPE i
      length   TYPE i
      progress TYPE abap_bool
    RAISING
      cx_static_check.
  METHODS cid_base32
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS cid_bases
    IMPORTING
      prefix              TYPE abap_bool
      numeric             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS cid_codecs
    IMPORTING
      numeric             TYPE abap_bool
      supported           TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS cid_format
    IMPORTING
      arg                 TYPE string
      f                   TYPE string
      v                   TYPE string
      mc                  TYPE string
      b                   TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS cid_hashes
    IMPORTING
      numeric             TYPE abap_bool
      supported           TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS commands
    IMPORTING
      flags               TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS commands_completion_bash
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS config
    IMPORTING
      arg                 TYPE string
      bool                TYPE abap_bool
      json                TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS config_edit
    RAISING
      cx_static_check.
  METHODS config_profile_apply
    IMPORTING
      arg                 TYPE string
      dry_run             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS config_replace
    RAISING
      cx_static_check.
  METHODS config_show
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS dag_export
    IMPORTING
      arg                 TYPE string
      progress            TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS dag_get
    IMPORTING
      arg                 TYPE string
      output_codec        TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS dag_import
    IMPORTING
      pin_roots           TYPE abap_bool
      silent              TYPE abap_bool
      stats               TYPE abap_bool
      allow_big_block     TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS dag_put
    IMPORTING
      store_codec         TYPE string
      input_codec         TYPE string
      pin                 TYPE abap_bool
      hash                TYPE string
      allow_big_block     TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS dag_resolve
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS dag_stat
    IMPORTING
      arg                 TYPE string
      progress            TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS dht_query
    IMPORTING
      arg                 TYPE string
      verbose             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.

  METHODS diag_cmds
    IMPORTING
      verbose             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS diag_cmds_clear
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS diag_cmds_set_time
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS diag_profile
    IMPORTING
      output                 TYPE string
      collectors             TYPE string
      profile_time           TYPE string
      mutex_profile_fraction TYPE i
      block_profile_rate     TYPE string
    EXPORTING
      ev_apiresponsestr      TYPE string
      ev_apiresponse         TYPE REF TO data
      ev_httpresponsecode    TYPE i
    RAISING
      cx_static_check.
  METHODS diag_sys
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS files_chcid
    IMPORTING
      arg                 TYPE string
      cid_version         TYPE i
      hash                TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS files_cp
    IMPORTING
      arg                 TYPE string
      parents             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS files_flush
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS files_ls
    IMPORTING
      arg                 TYPE string
      long                TYPE abap_bool
      u                   TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS files_mkdir
    IMPORTING
      arg                 TYPE string
      parents             TYPE abap_bool
      cid_version         TYPE i
      hash                TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS files_mv
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS files_read
    IMPORTING
      arg                 TYPE string
      offset              TYPE i
      count               TYPE i
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS files_rm
    IMPORTING
      arg                 TYPE string
      recursive           TYPE abap_bool
      force               TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS files_stat
    IMPORTING
      arg                 TYPE string
      format              TYPE string
      hash                TYPE abap_bool
      size                TYPE abap_bool
      with_local          TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS files_write
    IMPORTING
      arg                 TYPE string
      offset              TYPE i
      create              TYPE abap_bool
      parents             TYPE abap_bool
      truncate            TYPE abap_bool
      count               TYPE i
      raw_leaves          TYPE abap_bool
      cid_version         TYPE i
      hash                TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS filestore_dups
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS filestore_ls
    IMPORTING
      arg                 TYPE string
      file_order          TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS filestore_verify
    IMPORTING
      arg                 TYPE string
      file_order          TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS get
    IMPORTING
      arg                 TYPE string
      output              TYPE string
      archive             TYPE abap_bool
      compress            TYPE abap_bool
      compression_level   TYPE i
      progress            TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS id
    IMPORTING
      arg                 TYPE string
      format              TYPE string
      peerid_base         TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS key_export
    IMPORTING
      arg                 TYPE string
      output              TYPE string
      format              TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS key_gen
    IMPORTING
      arg                 TYPE string
      type                TYPE string
      size                TYPE i
      ipns_base           TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS key_import
    IMPORTING
      arg                 TYPE string
      ipns_base           TYPE string
      format              TYPE string
      allow_any_key_type  TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS key_list
    IMPORTING
      l                   TYPE abap_bool
      ipns_base           TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS key_rename
    IMPORTING
      arg                 TYPE string
      force               TYPE abap_bool
      ipns_base           TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS key_rm
    IMPORTING
      arg                 TYPE string
      l                   TYPE abap_bool
      ipns_base           TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS key_rotate
    IMPORTING
      oldkey              TYPE string
      type                TYPE string
      size                TYPE i
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS log_level
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS log_ls
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS ls
    IMPORTING
      arg                 TYPE string
      headers             TYPE abap_bool
      resolve_type        TYPE abap_bool
      size                TYPE abap_bool
      stream              TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS multibase_decode
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS multibase_encode
    IMPORTING
      b                   TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS multibase_list
    IMPORTING
      prefix              TYPE abap_bool
      numeric             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS multibase_transcode
    IMPORTING
      b                   TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS name_publish
    IMPORTING
      arg                 TYPE string
      resolve             TYPE abap_bool
      lifetime            TYPE string
      allow_offline       TYPE abap_bool
      ttl                 TYPE string
      key                 TYPE string
      quieter             TYPE abap_bool
      ipns_base           TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS name_resolve
    IMPORTING
      arg                 TYPE string
      recursive           TYPE abap_bool
      nocache             TYPE abap_bool
      dht_record_count    TYPE i
      dht_timeout         TYPE string
      stream              TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pin_add
    IMPORTING
      arg                 TYPE string
      recursive           TYPE abap_bool
      progress            TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pin_ls
    IMPORTING
      arg                 TYPE string
      type                TYPE string
      quiet               TYPE abap_bool
      stream              TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pin_remote_add
    IMPORTING
      arg                 TYPE string
      service             TYPE string
      name                TYPE string
      background          TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pin_remote_ls
    IMPORTING
      service             TYPE string
      name                TYPE string
      cid                 TYPE string
      status              TYPE  string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pin_remote_rm
    IMPORTING
      service             TYPE string
      name                TYPE string
      cid                 TYPE string
      status              TYPE string
      force               TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pin_remote_service_add
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pin_remote_service_ls
    IMPORTING
      stat                TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pin_remote_service_rm
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pin_rm
    IMPORTING
      arg                 TYPE string
      recursive           TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pin_update
    IMPORTING
      arg                 TYPE string
      unpin               TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pin_verify
    IMPORTING
      verbose             TYPE abap_bool
      quiet               TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS ping
    IMPORTING
      arg                 TYPE string
      count               TYPE i
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS refs
    IMPORTING
      arg                 TYPE string
      format              TYPE string
      edges               TYPE abap_bool
      unique              TYPE abap_bool
      recursive           TYPE abap_bool
      max_depth           TYPE i
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS refs_local
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS repo_gc
    IMPORTING
      stream_errors       TYPE abap_bool
      quiet               TYPE abap_bool
      silent              TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS repo_migrate
    IMPORTING
      allow_downgrade     TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS repo_stat
    IMPORTING
      size_only           TYPE abap_bool
      human               TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS repo_verify
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS repo_version
    IMPORTING
      quiet               TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS resolve
    IMPORTING
      arg                 TYPE string
      recursive           TYPE abap_bool
      dht_record_count    TYPE i
      dht_timeout         TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS routing_findpeer
    IMPORTING
      arg                 TYPE string
      verbose             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS routing_findprovs
    IMPORTING
      arg                 TYPE string
      verbose             TYPE abap_bool
      num_providers       TYPE i
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS routing_get
    IMPORTING
      arg                 TYPE string
      verbose             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS routing_provide
    IMPORTING
      arg                 TYPE string
      verbose             TYPE abap_bool
      recursive           TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS routing_put
    IMPORTING
      arg                 TYPE string
      verbose             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS shutdown
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS stats_bitswap
    IMPORTING
      verbose             TYPE abap_bool
      human               TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS stats_bw
    IMPORTING
      peer                TYPE string
      proto               TYPE string
      poll                TYPE abap_bool
      interval            TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS stats_dht
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS stats_provide
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS stats_repo
    IMPORTING
      size_only           TYPE abap_bool
      human               TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_addrs
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_addrs_listen
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_addrs_local
    IMPORTING
      id                  TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_connect
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_disconnect
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_filters
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_filters_add
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_filters_rm
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_peering_add
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_peering_ls
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_peering_rm
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_peers
    IMPORTING
      verbose             TYPE abap_bool
      streams             TYPE abap_bool
      latency             TYPE abap_bool
      direction           TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS update
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS version
    IMPORTING
      number              TYPE abap_bool
      commit              TYPE abap_bool
      repo                TYPE abap_bool
      all                 TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS version_deps
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS log_tail
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS mount
    IMPORTING
      ipfs_path           TYPE string
      ipns_path           TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS name_pubsub_cancel
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS name_pubsub_state
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS name_pubsub_subs
    IMPORTING
      ipns_base           TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS p2p_close
    IMPORTING
      all                 TYPE abap_bool
      protocol            TYPE string
      listen_address      TYPE string
      target_address      TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS p2p_forward
    IMPORTING
      arg                   TYPE string
      allow_custom_protocol TYPE abap_bool
    EXPORTING
      ev_apiresponsestr     TYPE string
      ev_apiresponse        TYPE REF TO data
      ev_httpresponsecode   TYPE i
    RAISING
      cx_static_check.
  METHODS p2p_listen
    IMPORTING
      arg                   TYPE string
      allow_custom_protocol TYPE abap_bool
      report_peer_id        TYPE abap_bool
    EXPORTING
      ev_apiresponsestr     TYPE string
      ev_apiresponse        TYPE REF TO data
      ev_httpresponsecode   TYPE i
    RAISING
      cx_static_check.
  METHODS p2p_ls
    IMPORTING
      headers             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS p2p_stream_close
    IMPORTING
      arg                 TYPE string
      all                 TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS p2p_stream_ls
    IMPORTING
      headers             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pubsub_ls
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pubsub_peers
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pubsub_pub
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS pubsub_sub
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_limit
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS swarm_stats
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS dht_findpeer
    IMPORTING
      arg                 TYPE string
      verbose             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS dht_findprovs
    IMPORTING
      arg                 TYPE string
      verbose             TYPE abap_bool
      num_providers       TYPE i
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS dht_get
    IMPORTING
      arg                 TYPE string
      verbose             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS dht_provide
    IMPORTING
      arg                 TYPE string
      verbose             TYPE abap_bool
      recursive           TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS dht_put
    IMPORTING
      arg                 TYPE string
      verbose             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS dns
    IMPORTING
      arg                 TYPE string
      recursive           TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS file_ls
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS object_data
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS object_diff
    IMPORTING
      arg                 TYPE string
      verbose             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS object_get
    IMPORTING
      arg                 TYPE string
      data_encoding       TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  .
  METHODS object_links
    IMPORTING
      arg                 TYPE string
      headers             TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS object_new
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS object_patch_add_link
    IMPORTING
      arg                 TYPE string
      create              TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS object_patch_append_data
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS object_patch_rm_link
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS object_patch_set_data
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS object_put
    IMPORTING
      inputenc            TYPE string
      datafieldenc        TYPE string
      pin                 TYPE abap_bool
      quiet               TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS object_stat
    IMPORTING
      arg                 TYPE string
      human               TYPE abap_bool
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS repo_fsck
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS tar_add
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
  METHODS tar_cat
    IMPORTING
      arg                 TYPE string
    EXPORTING
      ev_apiresponsestr   TYPE string
      ev_apiresponse      TYPE REF TO data
      ev_httpresponsecode TYPE i
    RAISING
      cx_static_check.
ENDINTERFACE.
