*&---------------------------------------------------------------------*
*& Include zproubc_vault_test_top
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK frame1 WITH FRAME TITLE TEXT-001.
  SELECTION-SCREEN ULINE /10(40).

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 15.
    PARAMETERS: rb1 RADIOBUTTON GROUP rb.
    SELECTION-SCREEN COMMENT 20(30) TEXT-002.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 15.
    PARAMETERS: rb2 RADIOBUTTON GROUP rb.
    SELECTION-SCREEN COMMENT 20(30) TEXT-003.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 15.
    PARAMETERS: rb3 RADIOBUTTON GROUP rb.
    SELECTION-SCREEN COMMENT 20(30) TEXT-004.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 15.
    PARAMETERS: rb4 RADIOBUTTON GROUP rb.
    SELECTION-SCREEN COMMENT 20(30) TEXT-005.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 15.
    PARAMETERS: rb5 RADIOBUTTON GROUP rb.
    SELECTION-SCREEN COMMENT 20(30) TEXT-006.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 15.
    PARAMETERS: rb6 RADIOBUTTON GROUP rb.
    SELECTION-SCREEN COMMENT 20(30) TEXT-007.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 15.
    PARAMETERS: rb7 RADIOBUTTON GROUP rb.
    SELECTION-SCREEN COMMENT 20(30) TEXT-008.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 15.
    PARAMETERS: rb8 RADIOBUTTON GROUP rb.
    SELECTION-SCREEN COMMENT 20(30) TEXT-009.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 15.
    PARAMETERS: rb9 RADIOBUTTON GROUP rb.
    SELECTION-SCREEN COMMENT 20(30) TEXT-010.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN POSITION 15.
    PARAMETERS: rb10 RADIOBUTTON GROUP rb.
    SELECTION-SCREEN COMMENT 20(30) TEXT-011.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN ULINE /10(40).
SELECTION-SCREEN END OF BLOCK frame1.
